import "./globals.css";

import type { Metadata } from "next";
import localFont from "next/font/local";

import { HeroUIProviderWrapper } from "../components/HeroUIProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* this layout act like a root-shell gives the context of it's children*/}
        <HeroUIProviderWrapper>{children}</HeroUIProviderWrapper>
      </body>
    </html>
  );
}
